version: '3'
services:
  web-app:
    build: .
    command: sh -c 'npm install; npm start'
    ports:
      - '3000:3000'
    depends_on:
      - "db-redis"
  db-redis:
    image: redis
    ports:
      - '6379:6379'
